let countries = [
{name: ["Afghanistan"], capital:["Kabul"], code:"AF"},
{name: ["Ägypten"], capital:["Kairo"], code:"EG"},
{name: ["Albanien"], capital:["Tirana"], code:"AL"},
{name: ["Algerien"], capital:["Algier"], code:"DZ"},
{name: ["Andorra"], capital:["Anodrra la Vella"], code:"AD"},
{name: ["Angola"], capital:["Luanda"], code:"AO"},
{name: ["Antigua und Barbuda"], capital:["Saint John's"], code:"AG"},
{name: ["Äquatorialguinea"], capital:["Malabo", "Ciudad de la Paz"], code:"GQ"},
{name: ["Argentinien"], capital:["Buenos Aires"], code:"AR"},
{name: ["Armenien"], capital:["Jerewan"], code:"AM"},
{name: ["Aserbaidschan"], capital:["Baku"], code:"AZ"},
{name: ["Äthiopien"], capital:["Addis Abeba"], code:"ET"},
{name: ["Australien"], capital:["Canberra"], code:"AU"},
{name: ["Bahamas"], capital:["Nassau"], code:"BS"},
{name: ["Bahrain"], capital:["Manama"], code:"BH"},
{name: ["Bangladesch"], capital:["Dhaka"], code:"BD"},
{name: ["Barbados"], capital:["Bridgetown"], code:"BB"},
{name: ["Belarus", "Weißrussland"], capital:["Minsk"], code:"BY"},
{name: ["Belgien"], capital:["Brüssel"], code:"BE"},
{name: ["Belize"], capital:["Belmopan"], code:"BZ"},
{name: ["Benin"], capital:["Porto-Novo", "Porto Novo"], code:"BJ"},
{name: ["Bhutan"], capital:["Thimphu"], code:"BT"},
{name: ["Bolivien"], capital:["Sucre", "La Paz"], code:"BO"},
{name: ["Bosnien und Herzegowina"], capital:["Sarajevo"], code:"BA"},
{name: ["Botswana", "Botsuana"], capital:["Gaborone"], code:"BW"},
{name: ["Brasilien"], capital:["Brasília", "Brasilia"], code:"BR"},
{name: ["Brunei", "Brunei Darussalam"], capital:["Bandar Seri Begawan"], code:"BN"},
{name: ["Bulgarien"], capital:["Sofia"], code:"BG"},
{name: ["Burkina Faso"], capital:["Ouagadougou"], code:"BF"},
{name: ["Burundi"], capital:["Gitega"], code:"BI"},
{name: ["Kap Verde", "Cabo Verde"], capital:["Praia"], code:"CV"},
{name: ["Chile"], capital:["Santiago de Chile"], code:"CL"},
{name: ["China"], capital:["Peking"], code:"CN"},
{name: ["Cookinseln"], capital:["Avarua"], code:"CK"},
{name: ["Costa Rica"], capital:["San José", "San Jose"], code:"CR"},
{name: ["Elfenbeinküste", "Côte d'Ivoire"], capital:["Yamoussoukro", "Abidjan"], code:"CI"},
{name: ["Dänemark"], capital:["Kopenhagen"], code:"DK"},
{name: ["Deutschland"], capital:["Berlin"], code:"DE"},
{name: ["Dominica"], capital:["Roseau"], code:"DM"},
{name: ["Dominikanische Republik", "Dom Rep"], capital:["Santo Domingo"], code:"DO"},
{name: ["Dschibuti"], capital:["Dschibuti"], code:"DJ"},
{name: ["Ecuador"], capital:["Quito"], code:"EC"},
{name: ["El Salvador"], capital:["San Salvador"], code:"SV"},
{name: ["Eritrea"], capital:["Asmara"], code:"ER"},
{name: ["Estland"], capital:["Tallinn"], code:"EE"},
{name: ["Eswatini"], capital:["Mbabane"], code:"SZ"},
{name: ["Fidschi"], capital:["Suva"], code:"FJ"},
{name: ["Finnland"], capital:["Helsinki"], code:"FI"},
{name: ["Frankreich"], capital:["Paris"], code:"FR"},
{name: ["Gabun"], capital:["Libreville"], code:"GA"},
{name: ["Gambia"], capital:["Banjul"], code:"GM"},
{name: ["Georgien"], capital:["Tiflis"], code:"GE"},
{name: ["Ghana"], capital:["Accra"], code:"GH"},
{name: ["Grenada"], capital:["St. George's"], code:"GD"},
{name: ["Griechenland"], capital:["Athen"], code:"GR"},
{name: ["Großbritannien", "Das Vereinigte Königreich", "UK"], capital:["London"], code:"GB"},
{name: ["Guatemala"], capital:["Guatemala-Stadt", "Guatemala Stadt"], code:"GT"},
{name: ["Guinea"], capital:["Conakry"], code:"GN"},
{name: ["Guinea-Bissau", "Guinea Bissau"], capital:["Bissau"], code:"GW"},
{name: ["Guyana"], capital:["Georgetown"], code:"GY"},
{name: ["Haiti"], capital:["Port-au-Prince", "Port au Prince"], code:"HT"},
{name: ["Honduras"], capital:["Tegucigalpa"], code:"HN"},
{name: ["Indien"], capital:["Neu-Delhi", "Neu Delhi"], code:"IN"},
{name: ["Indonesien"], capital:["Jakarta"], code:"ID"},
{name: ["Irak"], capital:["Bagdad"], code:"IQ"},
{name: ["Iran"], capital:["Teheran"], code:"IR"},
{name: ["Irland"], capital:["Dublin"], code:"IE"},
{name: ["Island"], capital:["Reykjavík", "Reykjavik"], code:"IS"},
{name: ["Israel"], capital:["Jerusalem"], code:"IL"},
{name: ["Italien"], capital:["Rom"], code:"IT"},
{name: ["Jamaika"], capital:["Kingston"], code:"JM"},
{name: ["Japan"], capital:["Tokio"], code:"JP"},
{name: ["Jemen"], capital:["Sanaa", "Aden"], code:"YE"},
{name: ["Jordanien"], capital:["Amman"], code:"JO"},
{name: ["Kambodscha"], capital:["Phnom Penh"], code:"KH"},
{name: ["Kamerun"], capital:["Yaoundé", "Yaounde"], code:"CM"},
{name: ["Kanada"], capital:["Ottawa"], code:"CA"},
{name: ["Kasachstan"], capital:["Astana"], code:"KZ"},
{name: ["Katar"], capital:["Doha"], code:"QA"},
{name: ["Kenia"], capital:["Nairobi"], code:"KE"},
{name: ["Kirgisistan"], capital:["Bischkek"], code:"KG"},
{name: ["Kiribati"], capital:["South Tarawa"], code:"KI"},
{name: ["Kolumbien"], capital:["Bogotá", "Bogota"], code:"CO"},
{name: ["Komoren"], capital:["Moroni"], code:"KM"},
{name: ["Demokratische Republik Kongo"], capital:["Kinshasa"], code:"CD"},
{name: ["Republik Kongo"], capital:["Brazzaville"], code:"CG"},
{name: ["Nordkorea"], capital:["Pjöngjang"], code:"KP"},
{name: ["Südkorea"], capital:["Seoul"], code:"KR"},
{name: ["Kosovo"], capital:["Pristina"], code:"so"},
{name: ["Kroatien"], capital:["Zagreb"], code:"HR"},
{name: ["Kuba"], capital:["Havanna"], code:"CU"},
{name: ["Kuwait"], capital:["Kuwait"], code:"KW"},
{name: ["Laos"], capital:["Vientiane"], code:"LA"},
{name: ["Lesotho"], capital:["Maseru"], code:"LS"},
{name: ["Lettland"], capital:["Riga"], code:"LV"},
{name: ["Libanon"], capital:["Beirut"], code:"LB"},
{name: ["Liberia"], capital:["Monrovia"], code:"LR"},
{name: ["Libyen"], capital:["Tripolis"], code:"LY"},
{name: ["Liechtenstein"], capital:["Vaduz"], code:"LI"},
{name: ["Litauen"], capital:["Vilnius"], code:"LT"},
{name: ["Luxemburg"], capital:["Luxemburg"], code:"LU"},
{name: ["Madagaskar"], capital:["Antananarivo"], code:"MG"},
{name: ["Malawi"], capital:["Lilongwe"], code:"MW"},
{name: ["Malaysia"], capital:["Kuala Lumpur", "Putrajaya"], code:"MY"},
{name: ["Malediven"], capital:["Malé", "Male"], code:"MV"},
{name: ["Mali"], capital:["Bamako"], code:"ML"},
{name: ["Malta"], capital:["Valletta"], code:"MT"},
{name: ["Marokko"], capital:["Rabat"], code:"MA"},
{name: ["Marshallinseln"], capital:["Majuro"], code:"MH"},
{name: ["Mauretanien"], capital:["Nouakchott"], code:"MR"},
{name: ["Mauritius"], capital:["Port Louis"], code:"MU"},
{name: ["Mexiko"], capital:["Mexiko-Stadt", "Mexiko Stadt"], code:"MX"},
{name: ["Mikronesien"], capital:["Palikir"], code:"FM"},
{name: ["Moldawien", "Moldau"], capital:["Chisinau"], code:"MD"},
{name: ["Monaco"], capital:["Monaco"], code:"MC"},
{name: ["Mongolei"], capital:["Ulaanbaatar"], code:"MN"},
{name: ["Montenegro"], capital:["Podgorica"], code:"ME"},
{name: ["Mosambik"], capital:["Maputo"], code:"MZ"},
{name: ["Myanmar"], capital:["Naypyidaw"], code:"MM"},
{name: ["Namibia"], capital:["Windhoek"], code:"NA"},
{name: ["Nauru"], capital:["Yaren"], code:"NR"},
{name: ["Nepal"], capital:["Kathmandu"], code:"NP"},
{name: ["Neuseeland"], capital:["Wellington"], code:"NZ"},
{name: ["Nicaragua"], capital:["Managua"], code:"NI"},
{name: ["Niederlande"], capital:["Amsterdam"], code:"NL"},
{name: ["Niger"], capital:["Niamey"], code:"NE"},
{name: ["Nigeria"], capital:["Abuja"], code:"NG"},
{name: ["Norwegen"], capital:["Oslo"], code:"NO"},
{name: ["Oman"], capital:["Maskat"], code:"OM"},
{name: ["Österreich"], capital:["Wien"], code:"AT"},
{name: ["Pakistan"], capital:["Islamabad"], code:"PK"},
{name: ["Palau"], capital:["Ngerulmud"], code:"PW"},
{name: ["Panama"], capital:["Panama-Stadt", "Panama Stadt"], code:"PA"},
{name: ["Papua-Neuguinea", "Papua Neuguinea"], capital:["Port Moresby"], code:"PG"},
{name: ["Paraguay"], capital:["Asunción", "Ascuncion"], code:"PY"},
{name: ["Peru"], capital:["Lima"], code:"PE"},
{name: ["Philippinen"], capital:["Manila"], code:"PH"},
{name: ["Polen"], capital:["Warschau"], code:"PL"},
{name: ["Portugal"], capital:["Lissabon"], code:"PT"},
{name: ["Ruanda"], capital:["Kigali"], code:"RW"},
{name: ["Rumänien"], capital:["Bukarest"], code:"RO"},
{name: ["Russland"], capital:["Moskau"], code:"RU"},
{name: ["Salomonen"], capital:["Honiara"], code:"SB"},
{name: ["Sambia"], capital:["Lusaka"], code:"ZM"},
{name: ["Samoa"], capital:["Apia"], code:"WS"},
{name: ["San Marino"], capital:["San Marino"], code:"SM"},
{name: ["São Tomé und Príncipe", "Sao Tome und Principe"], capital:["São Tomé", "Sao Tome"], code:"ST"},
{name: ["Saudi Arabien", "Saudi-Arabien"], capital:["Riad"], code:"SA"},
{name: ["Schweden"], capital:["Stockholm"], code:"SE"},
{name: ["Schweiz"], capital:["Bern"], code:"CH"},
{name: ["Senegal"], capital:["Dakar"], code:"SN"},
{name: ["Serbien"], capital:["Belgrad"], code:"RS"},
{name: ["Seychellen"], capital:["Victoria"], code:"SC"},
{name: ["Sierra Leone"], capital:["Freetown"], code:"SL"},
{name: ["Simbabwe"], capital:["Harare"], code:"ZW"},
{name: ["Singapur"], capital:["Singapur"], code:"SG"},
{name: ["Slowakei"], capital:["Bratislava", "Pressburg"], code:"SK"},
{name: ["Slowenien"], capital:["Ljubljana", "Laibach"], code:"SI"},
{name: ["Somalia"], capital:["Mogadischu"], code:"SO"},
{name: ["Spanien"], capital:["Madrid"], code:"ES"},
{name: ["Sri Lanka"], capital:["Kotte", "Colombo", "Sri Jayewardenepura"], code:"LK"},
{name: ["St. Kitts und Nevis"], capital:["Basseterre"], code:"KN"},
{name: ["St. Lucia"], capital:["Castries"], code:"LC"},
{name: ["St. Vincent und die Grenadinen"], capital:["Kingstown"], code:"VC"},
{name: ["Südafrika"], capital:["Kapstadt", "Bloemfontein", "Pretoria"], code:"ZA"},
{name: ["Sudan"], capital:["Khartum"], code:"SD"},
{name: ["Südsudan"], capital:["Juba"], code:"SS"},
{name: ["Suriname"], capital:["Paramaribo"], code:"SR"},
{name: ["Syrien"], capital:["Damaskus"], code:"SY"},
{name: ["Tadschikistan"], capital:["Duschanbe"], code:"TJ"},
{name: ["Taiwan"], capital:["Taipeh"], code:"TW"},
{name: ["Tansania"], capital:["Dodoma", "Daressalam"], code:"TZ"},
{name: ["Thailand"], capital:["Bangkok"], code:"TH"},
{name: ["Osttimor", "Timor-Leste"], capital:["Dili"], code:"TL"},
{name: ["Togo"], capital:["Lomé", "Lome"], code:"TG"},
{name: ["Tonga"], capital:["Nuku'alofa", "Nukualofa"], code:"TO"},
{name: ["Trinidad und Tobago"], capital:["Port of Spain"], code:"TT"},
{name: ["Tschad"], capital:["N'Djamena", "NDjamena"], code:"TD"},
{name: ["Tschechien", "Tschechische Republik"], capital:["Prag"], code:"CZ"},
{name: ["Tunesien"], capital:["Tunis"], code:"TN"},
{name: ["Türkei"], capital:["Ankara"], code:"TR"},
{name: ["Turkmenistan"], capital:["Asgabat"], code:"TM"},
{name: ["Tuvalu"], capital:["Funafuti"], code:"TV"},
{name: ["Uganda"], capital:["Kampala"], code:"UG"},
{name: ["Ukraine"], capital:["Kiew"], code:"UA"},
{name: ["Ungarn"], capital:["Budapest"], code:"HU"},
{name: ["Uruguay"], capital:["Montevideo"], code:"UY"},
{name: ["Usbekistan"], capital:["Taschkent"], code:"UZ"},
{name: ["Vanuatu"], capital:["Port Vila"], code:"VU"},
{name: ["Vatikanstadt"], capital:["Vatikanstadt"], code:"VA"},
{name: ["Venezuela"], capital:["Caracas"], code:"VE"},
{name: ["Vereinigte Arabische Emirate", "VAE"], capital:["Abu Dhabi"], code:"AE"},
{name: ["USA", "US", "Vereinigte Staaten"], capital:["Washington, D.C.", "Washington"], code:"US"},
{name: ["Vietnam"], capital:["Hanoi"], code:"VN"},
{name: ["Zentralafrikanische Republik", "Zentralafrika"], capital:["Bangui"], code:"CF"},
{name: ["Zypern"], capital:["Nikosia"], code:"CY"},
]