let countries = [
{name: ["Afghanistan"], capital:["Kabul"], continent:"Asien", code:"AF"},
{name: ["Ägypten"], capital:["Kairo"], continent:"Afrika", code:"EG"},
{name: ["Albanien"], capital:["Tirana"], continent:"Europa", code:"AL"},
{name: ["Algerien"], capital:["Algier"], continent:"Afrika", code:"DZ"},
{name: ["Andorra"], capital:["Anodrra la Vella"], continent:"Europa", code:"AD"},
{name: ["Angola"], capital:["Luanda"], continent:"Afrika", code:"AO"},
{name: ["Antigua und Barbuda"], capital:["Saint John's"], continent:"Nordamerika", code:"AG"},
{name: ["Äquatorialguinea"], capital:["Malabo", "Ciudad de la Paz"], continent:"Afrika", code:"GQ"},
{name: ["Argentinien"], capital:["Buenos Aires"], continent:"Südamerika", code:"AR"},
{name: ["Armenien"], capital:["Jerewan"], continent:"Asien", code:"AM"},
{name: ["Aserbaidschan"], capital:["Baku"], continent:"Asien", code:"AZ"},
{name: ["Äthiopien"], capital:["Addis Abeba"], continent:"Afrika", code:"ET"},
{name: ["Australien"], capital:["Canberra"], continent:"Ozeanien", code:"AU"},
{name: ["Bahamas"], capital:["Nassau"], continent:"Nordamerika", code:"BS"},
{name: ["Bahrain"], capital:["Manama"], continent:"Asien", code:"BH"},
{name: ["Bangladesch"], capital:["Dhaka"], continent:"Asien", code:"BD"},
{name: ["Barbados"], capital:["Bridgetown"], continent:"Nordamerika", code:"BB"},
{name: ["Belarus", "Weißrussland"], capital:["Minsk"], continent:"Europa", code:"BY"},
{name: ["Belgien"], capital:["Brüssel"], continent:"Europa", code:"BE"},
{name: ["Belize"], capital:["Belmopan"], continent:"Nordamerika", code:"BZ"},
{name: ["Benin"], capital:["Porto-Novo", "Porto Novo"], continent:"Afrika", code:"BJ"},
{name: ["Bhutan"], capital:["Thimphu"], continent:"Asien", code:"BT"},
{name: ["Bolivien"], capital:["Sucre", "La Paz"], continent:"Südamerika", code:"BO"},
{name: ["Bosnien und Herzegowina"], capital:["Sarajevo"], continent:"Europa", code:"BA"},
{name: ["Botswana", "Botsuana"], capital:["Gaborone"], continent:"Afrika", code:"BW"},
{name: ["Brasilien"], capital:["Brasília", "Brasilia"], continent:"Südamerika", code:"BR"},
{name: ["Brunei", "Brunei Darussalam"], capital:["Bandar Seri Begawan"], continent:"Asien", code:"BN"},
{name: ["Bulgarien"], capital:["Sofia"], continent:"Europa", code:"BG"},
{name: ["Burkina Faso"], capital:["Ouagadougou"], continent:"Afrika", code:"BF"},
{name: ["Burundi"], capital:["Gitega"], continent:"Afrika", code:"BI"},
{name: ["Kap Verde", "Cabo Verde"], capital:["Praia"], continent:"Afrika", code:"CV"},
{name: ["Chile"], capital:["Santiago de Chile"], continent:"Südamerika", code:"CL"},
{name: ["China"], capital:["Peking"], continent:"Asien", code:"CN"},
{name: ["Cookinseln"], capital:["Avarua"], continent:"Ozeanien", code:"CK"},
{name: ["Costa Rica"], capital:["San José", "San Jose"], continent:"Nordamerika", code:"CR"},
{name: ["Elfenbeinküste", "Côte d'Ivoire"], capital:["Yamoussoukro", "Abidjan"], continent:"Afrika", code:"CI"},
{name: ["Dänemark"], capital:["Kopenhagen"], continent:"Europa", code:"DK"},
{name: ["Deutschland"], capital:["Berlin"], continent:"Europa", code:"DE"},
{name: ["Dominica"], capital:["Roseau"], continent:"Nordamerika", code:"DM"},
{name: ["Dominikanische Republik", "Dom Rep"], capital:["Santo Domingo"], continent:"Nordamerika", code:"DO"},
{name: ["Dschibuti"], capital:["Dschibuti"], continent:"Afrika", code:"DJ"},
{name: ["Ecuador"], capital:["Quito"], continent:"Südamerika", code:"EC"},
{name: ["El Salvador"], capital:["San Salvador"], continent:"Nordamerika", code:"SV"},
{name: ["Eritrea"], capital:["Asmara"], continent:"Afrika", code:"ER"},
{name: ["Estland"], capital:["Tallinn"], continent:"Europa", code:"EE"},
{name: ["Eswatini"], capital:["Mbabane"], continent:"Afrika", code:"SZ"},
{name: ["Fidschi"], capital:["Suva"], continent:"Ozeanien", code:"FJ"},
{name: ["Finnland"], capital:["Helsinki"], continent:"Europa", code:"FI"},
{name: ["Frankreich"], capital:["Paris"], continent:"Europa", code:"FR"},
{name: ["Gabun"], capital:["Libreville"], continent:"Afrika", code:"GA"},
{name: ["Gambia"], capital:["Banjul"], continent:"Afrika", code:"GM"},
{name: ["Georgien"], capital:["Tiflis"], continent:"Asien", code:"GE"},
{name: ["Ghana"], capital:["Accra"], continent:"Afrika", code:"GH"},
{name: ["Grenada"], capital:["St. George's"], continent:"Nordamerika", code:"GD"},
{name: ["Griechenland"], capital:["Athen"], continent:"Europa", code:"GR"},
{name: ["Großbritannien", "Das Vereinigte Königreich", "UK"], capital:["London"], continent:"Europa", code:"GB"},
{name: ["Guatemala"], capital:["Guatemala-Stadt", "Guatemala Stadt"], continent:"Nordamerika", code:"GT"},
{name: ["Guinea"], capital:["Conakry"], continent:"Afrika", code:"GN"},
{name: ["Guinea-Bissau", "Guinea Bissau"], capital:["Bissau"], continent:"Afrika", code:"GW"},
{name: ["Guyana"], capital:["Georgetown"], continent:"Südamerika", code:"GY"},
{name: ["Haiti"], capital:["Port-au-Prince", "Port au Prince"], continent:"Nordamerika", code:"HT"},
{name: ["Honduras"], capital:["Tegucigalpa"], continent:"Nordamerika", code:"HN"},
{name: ["Indien"], capital:["Neu-Delhi", "Neu Delhi"], continent:"Asien", code:"IN"},
{name: ["Indonesien"], capital:["Jakarta"], continent:"Asien", code:"ID"},
{name: ["Irak"], capital:["Bagdad"], continent:"Asien", code:"IQ"},
{name: ["Iran"], capital:["Teheran"], continent:"Asien", code:"IR"},
{name: ["Irland"], capital:["Dublin"], continent:"Europa", code:"IE"},
{name: ["Island"], capital:["Reykjavík", "Reykjavik"], continent:"Europa", code:"IS"},
{name: ["Israel"], capital:["Jerusalem"], continent:"Asien", code:"IL"},
{name: ["Italien"], capital:["Rom"], continent:"Europa", code:"IT"},
{name: ["Jamaika"], capital:["Kingston"], continent:"Nordamerika", code:"JM"},
{name: ["Japan"], capital:["Tokio"], continent:"Asien", code:"JP"},
{name: ["Jemen"], capital:["Sanaa", "Aden"], continent:"Asien", code:"YE"},
{name: ["Jordanien"], capital:["Amman"], continent:"Asien", code:"JO"},
{name: ["Kambodscha"], capital:["Phnom Penh"], continent:"Asien", code:"KH"},
{name: ["Kamerun"], capital:["Yaoundé", "Yaounde"], continent:"Afrika", code:"CM"},
{name: ["Kanada"], capital:["Ottawa"], continent:"Nordamerika", code:"CA"},
{name: ["Kasachstan"], capital:["Astana"], continent:"Asien", code:"KZ"},
{name: ["Katar"], capital:["Doha"], continent:"Asien", code:"QA"},
{name: ["Kenia"], capital:["Nairobi"], continent:"Afrika", code:"KE"},
{name: ["Kirgisistan"], capital:["Bischkek"], continent:"Asien", code:"KG"},
{name: ["Kiribati"], capital:["South Tarawa"], continent:"Ozeanien", code:"KI"},
{name: ["Kolumbien"], capital:["Bogotá", "Bogota"], continent:"Südamerika", code:"CO"},
{name: ["Komoren"], capital:["Moroni"], continent:"Afrika", code:"KM"},
{name: ["Kongo", "Demokratische Republik Kongo"], capital:["Kinshasa"], continent:"Afrika", code:"CD"},
{name: ["Republik Kongo"], capital:["Brazzaville"], continent:"Afrika", code:"CG"},
{name: ["Nordkorea"], capital:["Pjöngjang"], continent:"Asien", code:"KP"},
{name: ["Südkorea"], capital:["Seoul"], continent:"Asien", code:"KR"},
{name: ["Kosovo"], capital:["Pristina"], continent:"Europa", code:"so"},
{name: ["Kroatien"], capital:["Zagreb"], continent:"Europa", code:"HR"},
{name: ["Kuba"], capital:["Havanna"], continent:"Nordamerika", code:"CU"},
{name: ["Kuwait"], capital:["Kuwait"], continent:"Asien", code:"KW"},
{name: ["Laos"], capital:["Vientiane"], continent:"Asien", code:"LA"},
{name: ["Lesotho"], capital:["Maseru"], continent:"Afrika", code:"LS"},
{name: ["Lettland"], capital:["Riga"], continent:"Europa", code:"LV"},
{name: ["Libanon"], capital:["Beirut"], continent:"Asien", code:"LB"},
{name: ["Liberia"], capital:["Monrovia"], continent:"Afrika", code:"LR"},
{name: ["Libyen"], capital:["Tripolis"], continent:"Afrika", code:"LY"},
{name: ["Liechtenstein"], capital:["Vaduz"], continent:"Europa", code:"LI"},
{name: ["Litauen"], capital:["Vilnius"], continent:"Europa", code:"LT"},
{name: ["Luxemburg"], capital:["Luxemburg"], continent:"Europa", code:"LU"},
{name: ["Madagaskar"], capital:["Antananarivo"], continent:"Afrika", code:"MG"},
{name: ["Malawi"], capital:["Lilongwe"], continent:"Afrika", code:"MW"},
{name: ["Malaysia"], capital:["Kuala Lumpur", "Putrajaya"], continent:"Asien", code:"MY"},
{name: ["Malediven"], capital:["Malé", "Male"], continent:"Asien", code:"MV"},
{name: ["Mali"], capital:["Bamako"], continent:"Afrika", code:"ML"},
{name: ["Malta"], capital:["Valletta"], continent:"Europa", code:"MT"},
{name: ["Marokko"], capital:["Rabat"], continent:"Afrika", code:"MA"},
{name: ["Marshallinseln"], capital:["Majuro"], continent:"Ozeanien", code:"MH"},
{name: ["Mauretanien"], capital:["Nouakchott"], continent:"Afrika", code:"MR"},
{name: ["Mauritius"], capital:["Port Louis"], continent:"Afrika", code:"MU"},
{name: ["Mexiko"], capital:["Mexiko-Stadt", "Mexiko Stadt"], continent:"Nordamerika", code:"MX"},
{name: ["Mikronesien"], capital:["Palikir"], continent:"Ozeanien", code:"FM"},
{name: ["Moldawien", "Moldau"], capital:["Chisinau"], continent:"Europa", code:"MD"},
{name: ["Monaco"], capital:["Monaco"], continent:"Europa", code:"MC"},
{name: ["Mongolei"], capital:["Ulaanbaatar"], continent:"Asien", code:"MN"},
{name: ["Montenegro"], capital:["Podgorica"], continent:"Europa", code:"ME"},
{name: ["Mosambik"], capital:["Maputo"], continent:"Afrika", code:"MZ"},
{name: ["Myanmar"], capital:["Naypyidaw"], continent:"Asien", code:"MM"},
{name: ["Namibia"], capital:["Windhoek"], continent:"Afrika", code:"NA"},
{name: ["Nauru"], capital:["Yaren"], continent:"Ozeanien", code:"NR"},
{name: ["Nepal"], capital:["Kathmandu"], continent:"Asien", code:"NP"},
{name: ["Neuseeland"], capital:["Wellington"], continent:"Ozeanien", code:"NZ"},
{name: ["Nicaragua"], capital:["Managua"], continent:"Nordamerika", code:"NI"},
{name: ["Niederlande"], capital:["Amsterdam"], continent:"Europa", code:"NL"},
{name: ["Niger"], capital:["Niamey"], continent:"Afrika", code:"NE"},
{name: ["Nigeria"], capital:["Abuja"], continent:"Afrika", code:"NG"},
{name: ["Norwegen"], capital:["Oslo"], continent:"Europa", code:"NO"},
{name: ["Nordmazedonien"], capital:["Skopje"], continent:"Europa", code:"MK"},
{name: ["Oman"], capital:["Maskat"], continent:"Asien", code:"OM"},
{name: ["Österreich"], capital:["Wien"], continent:"Europa", code:"AT"},
{name: ["Pakistan"], capital:["Islamabad"], continent:"Asien", code:"PK"},
{name: ["Palau"], capital:["Ngerulmud"], continent:"Ozeanien", code:"PW"},
{name: ["Panama"], capital:["Panama-Stadt", "Panama Stadt"], continent:"Nordamerika", code:"PA"},
{name: ["Papua-Neuguinea", "Papua Neuguinea"], capital:["Port Moresby"], continent:"Ozeanien", code:"PG"},
{name: ["Paraguay"], capital:["Asunción", "Ascuncion"], continent:"Südamerika", code:"PY"},
{name: ["Peru"], capital:["Lima"], continent:"Südamerika", code:"PE"},
{name: ["Philippinen"], capital:["Manila"], continent:"Asien", code:"PH"},
{name: ["Polen"], capital:["Warschau"], continent:"Europa", code:"PL"},
{name: ["Portugal"], capital:["Lissabon"], continent:"Europa", code:"PT"},
{name: ["Ruanda"], capital:["Kigali"], continent:"Afrika", code:"RW"},
{name: ["Rumänien"], capital:["Bukarest"], continent:"Europa", code:"RO"},
{name: ["Russland"], capital:["Moskau"], continent:"Europa", code:"RU"},
{name: ["Salomonen"], capital:["Honiara"], continent:"Ozeanien", code:"SB"},
{name: ["Sambia"], capital:["Lusaka"], continent:"Afrika", code:"ZM"},
{name: ["Samoa"], capital:["Apia"], continent:"Ozeanien", code:"WS"},
{name: ["San Marino"], capital:["San Marino"], continent:"Europa", code:"SM"},
{name: ["São Tomé und Príncipe", "Sao Tome und Principe"], capital:["São Tomé", "Sao Tome"], continent:"Afrika", code:"ST"},
{name: ["Saudi Arabien", "Saudi-Arabien"], capital:["Riad"], continent:"Asien", code:"SA"},
{name: ["Schweden"], capital:["Stockholm"], continent:"Europa", code:"SE"},
{name: ["Schweiz"], capital:["Bern"], continent:"Europa", code:"CH"},
{name: ["Senegal"], capital:["Dakar"], continent:"Afrika", code:"SN"},
{name: ["Serbien"], capital:["Belgrad"], continent:"Europa", code:"RS"},
{name: ["Seychellen"], capital:["Victoria"], continent:"Afrika", code:"SC"},
{name: ["Sierra Leone"], capital:["Freetown"], continent:"Afrika", code:"SL"},
{name: ["Simbabwe"], capital:["Harare"], continent:"Afrika", code:"ZW"},
{name: ["Singapur"], capital:["Singapur"], continent:"Asien", code:"SG"},
{name: ["Slowakei"], capital:["Bratislava", "Pressburg"], continent:"Europa", code:"SK"},
{name: ["Slowenien"], capital:["Ljubljana", "Laibach"], continent:"Europa", code:"SI"},
{name: ["Somalia"], capital:["Mogadischu"], continent:"Afrika", code:"SO"},
{name: ["Spanien"], capital:["Madrid"], continent:"Europa", code:"ES"},
{name: ["Sri Lanka"], capital:["Kotte", "Colombo", "Sri Jayewardenepura"], continent:"Asien", code:"LK"},
{name: ["St. Kitts und Nevis"], capital:["Basseterre"], continent:"Nordamerika", code:"KN"},
{name: ["St. Lucia"], capital:["Castries"], continent:"Nordamerika", code:"LC"},
{name: ["St. Vincent und die Grenadinen"], capital:["Kingstown"], continent:"Nordamerika", code:"VC"},
{name: ["Südafrika"], capital:["Kapstadt", "Bloemfontein", "Pretoria"], continent:"Afrika", code:"ZA"},
{name: ["Sudan"], capital:["Khartum"], continent:"Afrika", code:"SD"},
{name: ["Südsudan"], capital:["Juba"], continent:"Afrika", code:"SS"},
{name: ["Suriname"], capital:["Paramaribo"], continent:"Südamerika", code:"SR"},
{name: ["Syrien"], capital:["Damaskus"], continent:"Asien", code:"SY"},
{name: ["Tadschikistan"], capital:["Duschanbe"], continent:"Asien", code:"TJ"},
{name: ["Taiwan"], capital:["Taipeh"], continent:"Asien", code:"TW"},
{name: ["Tansania"], capital:["Dodoma", "Daressalam"], continent:"Afrika", code:"TZ"},
{name: ["Thailand"], capital:["Bangkok"], continent:"Asien", code:"TH"},
{name: ["Osttimor", "Timor-Leste"], capital:["Dili"], continent:"Asien", code:"TL"},
{name: ["Togo"], capital:["Lomé", "Lome"], continent:"Afrika", code:"TG"},
{name: ["Tonga"], capital:["Nuku'alofa", "Nukualofa"], continent:"Ozeanien", code:"TO"},
{name: ["Trinidad und Tobago"], capital:["Port of Spain"], continent:"Nordamerika", code:"TT"},
{name: ["Tschad"], capital:["N'Djamena", "NDjamena"], continent:"Afrika", code:"TD"},
{name: ["Tschechien", "Tschechische Republik"], capital:["Prag"], continent:"Europa", code:"CZ"},
{name: ["Tunesien"], capital:["Tunis"], continent:"Afrika", code:"TN"},
{name: ["Türkei"], capital:["Ankara"], continent:"Asien", code:"TR"},
{name: ["Turkmenistan"], capital:["Asgabat"], continent:"Asien", code:"TM"},
{name: ["Tuvalu"], capital:["Funafuti"], continent:"Ozeanien", code:"TV"},
{name: ["Uganda"], capital:["Kampala"], continent:"Afrika", code:"UG"},
{name: ["Ukraine"], capital:["Kiew"], continent:"Europa", code:"UA"},
{name: ["Ungarn"], capital:["Budapest"], continent:"Europa", code:"HU"},
{name: ["Uruguay"], capital:["Montevideo"], continent:"Südamerika", code:"UY"},
{name: ["Usbekistan"], capital:["Taschkent"], continent:"Asien", code:"UZ"},
{name: ["Vanuatu"], capital:["Port Vila"], continent:"Ozeanien", code:"VU"},
{name: ["Vatikanstadt"], capital:["Vatikanstadt"], continent:"Europa", code:"VA"},
{name: ["Venezuela"], capital:["Caracas"], continent:"Südamerika", code:"VE"},
{name: ["Vereinigte Arabische Emirate", "VAE"], capital:["Abu Dhabi"], continent:"Asien", code:"AE"},
{name: ["USA", "US", "Vereinigte Staaten"], capital:["Washington, D.C.", "Washington"], continent:"Nordamerika", code:"US"},
{name: ["Vietnam"], capital:["Hanoi"], continent:"Asien", code:"VN"},
{name: ["Zentralafrikanische Republik", "Zentralafrika"], capital:["Bangui"], continent:"Afrika", code:"CF"},
{name: ["Zypern"], capital:["Nikosia"], continent:"Europa", code:"CY"},
]