let countries = [
{name: ["Afghanistan"], capital:"", code:"AF"},
{name: ["Ägypten"], capital:"", code:"EG"},
{name: ["Albanien"], capital:"", code:"AL"},
{name: ["Algerien"], capital:"", code:"DZ"},
{name: ["Andorra"], capital:"", code:"AD"},
{name: ["Angola"], capital:"", code:"AO"},
{name: ["Antigua und Barbuda"], capital:"", code:"AG"},
{name: ["Äquatorialguinea"], capital:"", code:"GQ"},
{name: ["Argentinie"], capital:"", code:"AR"},
{name: ["Armenie"], capital:"", code:"AM"},
{name: ["Aserbaidschan"], capital:"", code:"AZ"},
{name: ["Äthiopien"], capital:"", code:"ET"},
{name: ["Australien"], capital:"", code:"AU"},
{name: ["Bahamas"], capital:"", code:"BS"},
{name: ["Bahrain"], capital:"", code:"BH"},
{name: ["Bangladesch"], capital:"", code:"BD"},
{name: ["Barbados"], capital:"", code:"BB"},
{name: ["Belarur"], capital:"", code:"BY"},
{name: ["Belgien"], capital:"", code:"BE"},
{name: ["Belize"], capital:"", code:"BZ"},
{name: ["Benis"], capital:"", code:"BJ"},
{name: ["Bhutan"], capital:"", code:"BT"},
{name: ["Bolivien"], capital:"", code:"BO"},
{name: ["Bosnien und Herzegowina"], capital:"", code:"BA"},
{name: ["Botsuana"], capital:"", code:"BW"},
{name: ["Brasilien"], capital:"", code:"BR"},
{name: ["Brunei", "Brunei Darussalam"], capital:"", code:"BN"},
{name: ["Bulgarien"], capital:"", code:"BG"},
{name: ["Burkina Faso"], capital:"", code:"BF"},
{name: ["Burundi"], capital:"", code:"BI"},
{name: ["Cabo Verde"], capital:"", code:"CV"},
{name: ["Chile"], capital:"", code:"CL"},
{name: ["China"], capital:"", code:"CN"},
{name: ["Cookinseln"], capital:"", code:"CK"},
{name: ["Costa Rica"], capital:"", code:"CR"},
{name: ["Elfenbeinküste", "Côte d'Ivoire"], capital:"", code:"CI"},
{name: ["Dänemark"], capital:"", code:"DK"},
{name: ["Deutschland"], capital:"", code:"DE"},
{name: ["Dominica"], capital:"", code:"DM"},
{name: ["Dominikanische Republik"], capital:"", code:"DO"},
{name: ["Dschibuti"], capital:"", code:"DJ"},
{name: ["Ecuador"], capital:"", code:"EC"},
{name: ["El Salvador"], capital:"", code:"SV"},
{name: ["Eritrea"], capital:"", code:"ER"},
{name: ["Estland"], capital:"", code:"EE"},
{name: ["Eswatini"], capital:"", code:"SZ"},
{name: ["Fidschi"], capital:"", code:"FJ"},
{name: ["Finnland"], capital:"", code:"FI"},
{name: ["Frankreich"], capital:"", code:"FR"},
{name: ["Gabun"], capital:"", code:"GA"},
{name: ["Gambia"], capital:"", code:"GM"},
{name: ["Georgien"], capital:"", code:"GE"},
{name: ["Ghana	Die Republik"], capital:"", code:"GH"},
{name: ["Grenada"], capital:"", code:"GD"},
{name: ["Griechenland"], capital:"", code:"GR"},
{name: ["Großbritannien", "Das Vereinigte Königreich", "UK"], capital:"", code:"GB"},
{name: ["Guatemala"], capital:"", code:"GT"},
{name: ["Guinea"], capital:"", code:"GN"},
{name: ["Guinea-Bissau", "Guinea Bissau"], capital:"", code:"GW"},
{name: ["Guyana"], capital:"", code:"GY"},
{name: ["Haiti"], capital:"", code:"HT"},
{name: ["Honduras"], capital:"", code:"HN"},
{name: ["Indien"], capital:"", code:"IN"},
{name: ["Indonesien"], capital:"", code:"ID"},
{name: ["Irak"], capital:"", code:"IQ"},
{name: ["Iran	Die"], capital:"", code:"IR"},
{name: ["Irland"], capital:"", code:"IE"},
{name: ["Island"], capital:"", code:"IS"},
{name: ["Israel"], capital:"", code:"IL"},
{name: ["Italien"], capital:"", code:"IT"},
{name: ["Jamaika"], capital:"", code:"JM"},
{name: ["Japan"], capital:"", code:"JP"},
{name: ["Jemen"], capital:"", code:"YE"},
{name: ["Jordanien"], capital:"", code:"JO"},
{name: ["Kambodscha"], capital:"", code:"KH"},
{name: ["Kamerun"], capital:"", code:"CM"},
{name: ["Kanada"], capital:"", code:"CA"},
{name: ["Kasachstan"], capital:"", code:"KZ"},
{name: ["Katar"], capital:"", code:"QA"},
{name: ["Kenia"], capital:"", code:"KE"},
{name: ["Kirgisistan"], capital:"", code:"KG"},
{name: ["Kiribati"], capital:"", code:"KI"},
{name: ["Kolumbien"], capital:"", code:"CO"},
{name: ["Komoren"], capital:"", code:"KM"},
{name: ["Kongo"], capital:"", code:"CG"},
{name: ["Kongo"], capital:"", code:"CD"},
{name: ["VR Korea", "Volksrepublik Korea"], capital:"", code:"KP"},
{name: ["Korea"], capital:"", code:"KR"},
{name: ["Kosovo"], capital:"", code:"so"},
{name: ["Kroatien"], capital:"", code:"HR"},
{name: ["Kuba"], capital:"", code:"CU"},
{name: ["Kuwait"], capital:"", code:"KW"},
{name: ["Laos"], capital:"", code:"LA"},
{name: ["Lesotho"], capital:"", code:"LS"},
{name: ["Lettland"], capital:"", code:"LV"},
{name: ["Libanon"], capital:"", code:"LB"},
{name: ["Liberia"], capital:"", code:"LR"},
{name: ["Libyen"], capital:"", code:"LY"},
{name: ["Liechtenstein"], capital:"", code:"LI"},
{name: ["Litauen"], capital:"", code:"LT"},
{name: ["Luxemburg"], capital:"", code:"LU"},
{name: ["Madagaskar"], capital:"", code:"MG"},
{name: ["Malawi"], capital:"", code:"MW"},
{name: ["Malaysia"], capital:"", code:"MY"},
{name: ["Malediven"], capital:"", code:"MV"},
{name: ["Mali"], capital:"", code:"ML"},
{name: ["Malta"], capital:"", code:"MT"},
{name: ["Marokko"], capital:"", code:"MA"},
{name: ["Marshallinseln"], capital:"", code:"MH"},
{name: ["Mauretanien"], capital:"", code:"MR"},
{name: ["Mauritius"], capital:"", code:"MU"},
{name: ["Mexiko"], capital:"", code:"MX"},
{name: ["Mikronesien"], capital:"", code:"FM"},
{name: ["Moldau"], capital:"", code:"MD"},
{name: ["Monaco"], capital:"", code:"MC"},
{name: ["Mongolei"], capital:"", code:"MN"},
{name: ["Montenegro"], capital:"", code:"ME"},
{name: ["Mosambik"], capital:"", code:"MZ"},
{name: ["Myanmar"], capital:"", code:"MM"},
{name: ["Namibia"], capital:"", code:"NA"},
{name: ["Nauru"], capital:"", code:"NR"},
{name: ["Nepal"], capital:"", code:"NP"},
{name: ["Neuseeland"], capital:"", code:"NZ"},
{name: ["Nicaragua"], capital:"", code:"NI"},
{name: ["Niederlande"], capital:"", code:"NL"},
{name: ["Niger"], capital:"", code:"NE"},
{name: ["Nigeria"], capital:"", code:"NG"},
{name: ["Norwegen"], capital:"", code:"NO"},
{name: ["Oman"], capital:"", code:"OM"},
{name: ["Österreich"], capital:"", code:"AT"},
{name: ["Pakistan"], capital:"", code:"PK"},
{name: ["Palau"], capital:"", code:"PW"},
{name: ["Panama"], capital:"", code:"PA"},
{name: ["Papua-Neuguinea", "Papua Neuguinea"], capital:"", code:"PG"},
{name: ["Paraguay"], capital:"", code:"PY"},
{name: ["Peru"], capital:"", code:"PE"},
{name: ["Philippinen"], capital:"", code:"PH"},
{name: ["Polen"], capital:"", code:"PL"},
{name: ["Portugal"], capital:"", code:"PT"},
{name: ["Ruanda"], capital:"", code:"RW"},
{name: ["Rumänien"], capital:"", code:"RO"},
{name: ["Russische Föderation"], capital:"", code:"RU"},
{name: ["Salomonen"], capital:"", code:"SB"},
{name: ["Sambia"], capital:"", code:"ZM"},
{name: ["Samoa"], capital:"", code:"WS"},
{name: ["San Marino"], capital:"", code:"SM"},
{name: ["São Tomé und Príncipe", "Sao Tome und Principe"], capital:"", code:"ST"},
{name: ["Saudi Arabien", "Saudi-Arabien"], capital:"", code:"SA"},
{name: ["Schweden"], capital:"", code:"SE"},
{name: ["Schweiz"], capital:"", code:"CH"},
{name: ["Senegal"], capital:"", code:"SN"},
{name: ["Serbien"], capital:"", code:"RS"},
{name: ["Seychellen"], capital:"", code:"SC"},
{name: ["Sierra Leone"], capital:"", code:"SL"},
{name: ["Simbabwe"], capital:"", code:"ZW"},
{name: ["Singapur"], capital:"", code:"SG"},
{name: ["Slowakei"], capital:"", code:"SK"},
{name: ["Slowenien"], capital:"", code:"SI"},
{name: ["Somalia"], capital:"", code:"SO"},
{name: ["Spanien"], capital:"", code:"ES"},
{name: ["Sri Lanka"], capital:"", code:"LK"},
{name: ["St. Kitts und Nevis"], capital:"", code:"KN"},
{name: ["St. Lucia"], capital:"", code:"LC"},
{name: ["St. Vincent und die Grenadinen"], capital:"", code:"VC"},
{name: ["Südafrika"], capital:"", code:"ZA"},
{name: ["Sudan"], capital:"", code:"SD"},
{name: ["Südsudan"], capital:"", code:"SS"},
{name: ["Suriname"], capital:"", code:"SR"},
{name: ["Syrien"], capital:"", code:"SY"},
{name: ["Tadschikistan"], capital:"", code:"TJ"},
{name: ["Taiwan"], capital:"", code:"TW"},
{name: ["Tansania"], capital:"", code:"TZ"},
{name: ["Thailand"], capital:"", code:"TH"},
{name: ["Timor-Leste"], capital:"", code:"TL"},
{name: ["Togo"], capital:"", code:"TG"},
{name: ["Tonga"], capital:"", code:"TO"},
{name: ["Trinidad und Tobago"], capital:"", code:"TT"},
{name: ["Tschad"], capital:"", code:"TD"},
{name: ["Tschechien", "Tschechische Republik"], capital:"", code:"CZ"},
{name: ["Tunesien"], capital:"", code:"TN"},
{name: ["Türkei"], capital:"", code:"TR"},
{name: ["Turkmenistan"], capital:"", code:"TM"},
{name: ["Tuvalu"], capital:"", code:"TV"},
{name: ["Uganda"], capital:"", code:"UG"},
{name: ["Ukraine"], capital:"", code:"UA"},
{name: ["Ungarn"], capital:"", code:"HU"},
{name: ["Uruguay"], capital:"", code:"UY"},
{name: ["Usbekistan"], capital:"", code:"UZ"},
{name: ["Vanuatu"], capital:"", code:"VU"},
{name: ["Vatikanstadt"], capital:"", code:"VA"},
{name: ["Venezuela"], capital:"", code:"VE"},
{name: ["Vereinigte Arabische Emirate", "VAE"], capital:"", code:"AE"},
{name: ["USA", "US", "Vereinigte Staaten"], capital:"", code:"US"},
{name: ["Vietnam"], capital:"", code:"VN"},
{name: ["Zentralafrikanische Republik"], capital:"", code:"CF"},
{name: ["Zypern"], capital:"", code:"CY"},
]