let countries = [
{name: ["Afghanistan"], code: "AF"},
{name: ["Ägypten"], code: "EG"},
{name: ["Åland", "Aland"], code: "AX"},
{name: ["Albanien"], code: "AL"},
{name: ["Algerien"], code: "DZ"},
{name: ["Amerikanische Jungferninseln", "US Jungferninseln", "USA Jungferninseln"], code: "VI"},
{name: ["Amerikanisch-Samoa"], code: "AS"},
{name: ["Andorra"], code: "AD"},
{name: ["Angola"], code: "AO"},
{name: ["Anguilla"], code: "AI"},
{name: ["Antarktika"], code: "AQ"},
{name: ["Antigua und Barbuda", "Antigua Barbuda", "Antigua & Barbuda"], code: "AG"},
{name: ["Äquatorialguinea"], code: "GQ"},
{name: ["Argentinien"], code: "AR"},
{name: ["Armenien"], code: "AM"},
{name: ["Aruba"], code: "AW"},
{name: ["Aserbaidschan"], code: "AZ"},
{name: ["Äthiopien"], code: "ET"},
{name: ["Australien"], code: "AU"},
{name: ["Bahamas"], code: "BS"},
{name: ["Bahrain"], code: "BH"},
{name: ["Bangladesch"], code: "BD"},
{name: ["Barbados"], code: "BB"},
{name: ["Belarus", "Weissrussland", "Weißrussland"], code: "BY"},
{name: ["Belgien"], code: "BE"},
{name: ["Belize"], code: "BZ"},
{name: ["Benin"], code: "BJ"},
{name: ["Bermuda"], code: "BM"},
{name: ["Bhutan"], code: "BT"},
{name: ["Bolivien"], code: "BO"},
{name: ["Bosnien und Herzegowina", "Bosnien Herzegowina", "Bosnien & Herzegowina"], code: "BA"},
{name: ["Botsuana"], code: "BW"},
{name: ["Bouvetinsel"], code: "BV"},
{name: ["Brasilien"], code: "BR"},
{name: ["Britische Jungferninseln", "UK Jungferninseln"], code: "VG"},
{name: ["Britisches Territorium im Indischen Ozean", "wtf"], code: "IO"},
{name: ["Brunei", "Brunei Darussalam"], code: "BN"},
{name: ["Bulgarien"], code: "BG"},
{name: ["Burkina Faso"], code: "BF"},
{name: ["Burundi"], code: "BI"},
{name: ["Cabo Verde", "Kap Verde"], code: "CV"},
{name: ["Chile"], code: "CL"},
{name: ["China"], code: "CN"},
{name: ["Cookinseln"], code: "CK"},
{name: ["Costa Rica"], code: "CR"},
{name: ["Elfenbeinküste", "Côte d'Ivoire", "Cote dIvoire", "Cote d'Ivoire"], code: "CI"},
{name: ["Dänemark"], code: "DK"},
{name: ["Deutschland"], code: "DE"},
{name: ["Dominica"], code: "DM"},
{name: ["Dominikanische Republik", "Dominika"], code: "DO"},
{name: ["Dschibuti"], code: "DJ"},
{name: ["Ecuador"], code: "EC"},
{name: ["El Salvador", "salvador"], code: "SV"},
{name: ["Eritrea"], code: "ER"},
{name: ["Estland"], code: "EE"},
{name: ["Eswatini"], code: "SZ"},
{name: ["Falklandinseln"], code: "FK"},
{name: ["Färöer"], code: "FO"},
{name: ["Fidschi"], code: "FJ"},
{name: ["Finnland"], code: "FI"},
{name: ["Frankreich"], code: "FR"},
{name: ["Französisch-Guayana", "Französisch Guayana"], code: "GF"},
{name: ["Französisch-Polynesien", "Französisch Polynesien"], code: "PF"},
{name: ["Gabun"], code: "GA"},
{name: ["Gambia"], code: "GM"},
{name: ["Georgien"], code: "GE"},
{name: ["Ghana"], code: "GH"},
{name: ["Gibraltar"], code: "GI"},
{name: ["Grenada"], code: "GD"},
{name: ["Griechenland"], code: "GR"},
{name: ["Grönland"], code: "GL"},
{name: ["Großbritannien", "UK", "Britannien"], code: "GB"},
{name: ["Guadeloupe"], code: "GP"},
{name: ["Guam"], code: "GU"},
{name: ["Guatemala"], code: "GT"},
{name: ["Guernsey"], code: "GG"},
{name: ["Guinea"], code: "GN"},
{name: ["Guinea-Bissau", "Guinea Bissau"], code: "GW"},
{name: ["Guyana"], code: "GY"},
{name: ["Haiti"], code: "HT"},
{name: ["Heard und McDonaldinseln", "McDonaldinseln", "Heard McDonaldinseln", "Heard & McDonaldinseln"], code: "HM"},
{name: ["Honduras"], code: "HN"},
{name: ["Hongkong"], code: "HK"},
{name: ["Indien"], code: "IN"},
{name: ["Indonesien"], code: "ID"},
{name: ["Insel Man", "isle of man"], code: "IM"},
{name: ["Irak"], code: "IQ"},
{name: ["Iran"], code: "IR"},
{name: ["Irland"], code: "IE"},
{name: ["Island"], code: "IS"},
{name: ["Israel"], code: "IL"},
{name: ["Italien"], code: "IT"},
{name: ["Jamaika"], code: "JM"},
{name: ["Japan"], code: "JP"},
{name: ["Jemen"], code: "YE"},
{name: ["Jersey"], code: "JE"},
{name: ["Jordanien"], code: "JO"},
{name: ["Kaimaninseln"], code: "KY"},
{name: ["Kambodscha"], code: "KH"},
{name: ["Kamerun"], code: "CM"},
{name: ["Kanada"], code: "CA"},
{name: ["Kasachstan"], code: "KZ"},
{name: ["Katar"], code: "QA"},
{name: ["Kenia"], code: "KE"},
{name: ["Kirgisistan"], code: "KG"},
{name: ["Kiribati"], code: "KI"},
{name: ["Kleinere Amerikanische Überseeinseln"], code: "UM"},
{name: ["Kokosinseln", "Keelinginseln"], code: "CC"},
{name: ["Kolumbien"], code: "CO"},
{name: ["Komoren"], code: "KM"},
{name: ["Kongo"], code: "CG"},
{name: ["Kongo", "Demokratische Republik Kongo"], code: "CD"},
{name: ["Nordkorea"], code: "KP"},
{name: ["Südkorea"], code: "KR"},
{name: ["Kroatien"], code: "HR"},
{name: ["Kuba"], code: "CU"},
{name: ["Kuwait"], code: "KW"},
{name: ["Laos"], code: "LA"},
{name: ["Lesotho"], code: "LS"},
{name: ["Lettland"], code: "LV"},
{name: ["Libanon"], code: "LB"},
{name: ["Liberia"], code: "LR"},
{name: ["Libyen"], code: "LY"},
{name: ["Liechtenstein"], code: "LI"},
{name: ["Litauen"], code: "LT"},
{name: ["Luxemburg"], code: "LU"},
{name: ["Macau"], code: "MO"},
{name: ["Madagaskar"], code: "MG"},
{name: ["Malawi"], code: "MW"},
{name: ["Malaysia"], code: "MY"},
{name: ["Malediven"], code: "MV"},
{name: ["Mali"], code: "ML"},
{name: ["Malta"], code: "MT"},
{name: ["Marokko"], code: "MA"},
{name: ["Marshallinseln"], code: "MH"},
{name: ["Martinique"], code: "MQ"},
{name: ["Mauretanien"], code: "MR"},
{name: ["Mauritius"], code: "MU"},
{name: ["Mayotte"], code: "YT"},
{name: ["Mexiko"], code: "MX"},
{name: ["Mikronesien"], code: "FM"},
{name: ["Moldau"], code: "MD"},
{name: ["Monaco"], code: "MC"},
{name: ["Mongolei"], code: "MN"},
{name: ["Montenegro"], code: "ME"},
{name: ["Montserrat"], code: "MS"},
{name: ["Mosambik"], code: "MZ"},
{name: ["Myanmar"], code: "MM"},
{name: ["Namibia"], code: "NA"},
{name: ["Nauru"], code: "NR"},
{name: ["Nepal"], code: "NP"},
{name: ["Neukaledonien"], code: "NC"},
{name: ["Neuseeland"], code: "NZ"},
{name: ["Nicaragua"], code: "NI"},
{name: ["Niederlande"], code: "NL"},
{name: ["Niger"], code: "NE"},
{name: ["Nigeria"], code: "NG"},
{name: ["Niue"], code: "NU"},
{name: ["Nördliche Marianen"], code: "MP"},
{name: ["Nordmazedonien"], code: "MK"},
{name: ["Norfolkinsel"], code: "NF"},
{name: ["Norwegen"], code: "NO"},
{name: ["Oman"], code: "OM"},
{name: ["Österreich", "Ostarichi"], code: "AT"},
{name: ["Pakistan"], code: "PK"},
{name: ["Palau"], code: "PW"},
{name: ["Panama"], code: "PA"},
{name: ["Papua-Neuguinea", "Papua Neuguinea", "Papua"], code: "PG"},
{name: ["Paraguay"], code: "PY"},
{name: ["Peru"], code: "PE"},
{name: ["Philippinen"], code: "PH"},
{name: ["Pitcairninseln"], code: "PN"},
{name: ["Polen"], code: "PL"},
{name: ["Portugal"], code: "PT"},
{name: ["Puerto Rico"], code: "PR"},
{name: ["Réunion", "Reunion"], code: "RE"},
{name: ["Ruanda"], code: "RW"},
{name: ["Rumänien"], code: "RO"},
{name: ["Russische Föderation", "russland"], code: "RU"},
{name: ["Salomonen"], code: "SB"},
{name: ["Sambia"], code: "ZM"},
{name: ["Samoa"], code: "WS"},
{name: ["San Marino"], code: "SM"},
{name: ["São Tomé und Príncipe", "Sao Tome und Principe"], code: "ST"},
{name: ["Saudi-Arabien", "Saudi Arabien"], code: "SA"},
{name: ["Schweden"], code: "SE"},
{name: ["Schweiz"], code: "CH"},
{name: ["Senegal"], code: "SN"},
{name: ["Serbien"], code: "RS"},
{name: ["Seychellen"], code: "SC"},
{name: ["Sierra Leone"], code: "SL"},
{name: ["Simbabwe"], code: "ZW"},
{name: ["Singapur"], code: "SG"},
{name: ["Slowakei"], code: "SK"},
{name: ["Slowenien"], code: "SI"},
{name: ["Somalia"], code: "SO"},
{name: ["Spanien"], code: "ES"},
{name: ["Spitzbergen"], code: "SJ"},
{name: ["Sri Lanka"], code: "LK"},
{name: ["St. Barthélemy", "St. Barthelemy"], code: "BL"},
{name: ["St. Helena, Ascension und Tristan da Cunha", "wtf"], code: "SH"},
{name: ["St. Kitts und Nevis"], code: "KN"},
{name: ["St. Lucia"], code: "LC"},
{name: ["St. Pierre und Miquelon"], code: "PM"},
{name: ["St. Vincent und die Grenadinen", "St. Vincent und Grenadinen", "Vincent und die Grenadinen"], code: "VC"},
{name: ["Südafrika"], code: "ZA"},
{name: ["Sudan"], code: "SD"},
{name: ["Südgeorgien und die Südlichen Sandwichinseln"], code: "GS"},
{name: ["Südsudan"], code: "SS"},
{name: ["Suriname"], code: "SR"},
{name: ["Syrien"], code: "SY"},
{name: ["Tadschikistan"], code: "TJ"},
{name: ["Taiwan"], code: "TW"},
{name: ["Tansania"], code: "TZ"},
{name: ["Thailand"], code: "TH"},
{name: ["Timor-Leste", "Timor Leste"], code: "TL"},
{name: ["Togo"], code: "TG"},
{name: ["Tokelau"], code: "TK"},
{name: ["Tonga"], code: "TO"},
{name: ["Trinidad und Tobago", "Trinidad & Tobago", "Trinidad Tobago"], code: "TT"},
{name: ["Tschad"], code: "TD"},
{name: ["Tschechische Republik", "Tschechien"], code: "CZ"},
{name: ["Tunesien"], code: "TN"},
{name: ["Türkei"], code: "TR"},
{name: ["Turkmenistan"], code: "TM"},
{name: ["Turks- und Caicosinseln", "Turksinseln und Caicosinseln", "Turksinseln & Caicosinseln", "Turksinseln Caicosinseln", "Turk und Caicosinseln"], code: "TC"},
{name: ["Tuvalu"], code: "TV"},
{name: ["Uganda"], code: "UG"},
{name: ["Ukraine"], code: "UA"},
{name: ["Ungarn"], code: "HU"},
{name: ["Uruguay"], code: "UY"},
{name: ["Usbekistan"], code: "UZ"},
{name: ["Vanuatu"], code: "VU"},
{name: ["Vatikanstadt", "Vatikan"], code: "VA"},
{name: ["Venezuela"], code: "VE"},
{name: ["Vereinigte Arabische Emirate", "UAE", "Arabien"], code: "AE"},
{name: ["Vereinigte Staaten", "US", "USA"], code: "US"},
{name: ["Vietnam"], code: "VN"},
{name: ["Wallis und Futuna", "Wallis & Futuna", "Wallis Futuna"], code: "WF"},
{name: ["Weihnachtsinsel"], code: "CX"},
{name: ["Westjordanland"], code: "PS"},
{name: ["Westsahara"], code: "EH"},
{name: ["Zentralafrikanische Republik", "Zentralafrika"], code: "CF"},
{name: ["Zypern"], code: "CY"}]